name: ${APP_NAME:-qcon-guide}
services:
  app:
    image: node:16-alpine

    command: sh -c "yarn install && yarn start"

    environment:
      # helps file watching work reliably in Docker on Mac/Windows
      - CHOKIDAR_USEPOLLING=true
      # - NODE_OPTIONS=--openssl-legacy-provider

    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules

    ports:
      - "3000:3000"

    stdin_open: true
    tty: true
